import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
import { auditCsv, identityCsv, sha256 } from "../src/lib/imports/csv";
import { mergeInputs, readRows, rowProblem } from "../src/lib/imports/types";
import { parseReviewCsv } from "../src/features/import/csv";
import { computeXray } from "../src/lib/xray/compute";

async function main() {
 const a={ticker:"AAPL",name:"Apple",kind:"stock" as const,shares:0.1,marketValue:null,valuationDate:""};
 const b={...a,shares:0.2};
 assert.equal(identityCsv([a,b]),identityCsv([{...a,shares:0.3}]));
 assert.equal(identityCsv([a,b]),identityCsv([b,a]));
 assert.equal(identityCsv([a]),identityCsv([{...a,marketValue:200,valuationDate:"2026-01-01"}]));
 assert.notEqual(sha256(auditCsv([a])),sha256(auditCsv([{...a,marketValue:200}])));
 assert.equal(readRows(Array.from({length:120},()=>a)).length,120);
 assert.equal(readRows([{ticker:"???"},null]).length,2);
 assert.ok(rowProblem(readRows([{ticker:"???"}])[0]));
 assert.ok(rowProblem({...a,excluded:true}));
 assert.equal(rowProblem({...a,excluded:true,exclusionReason:"Summary total, not a holding"}),null);
 assert.equal(parseReviewCsv('Symbol,Quantity,Value\nAAPL,1,100\nAAPL,2,200\nCASH,,300\n???,,400').rows.length,4);
 const model=computeXray([{ticker:"AAPL",name:"Apple",shares:1,price:50,kind:"stock"},{ticker:"USD",name:"USD",shares:50,price:1,kind:"cash"}]);
 assert.equal(model.total,100);assert.equal(model.topTen.length,1);assert.equal(model.topTen[0].value,50);
 assert.equal(computeXray([{ticker:"USD",name:"Cash",shares:100,price:1,kind:"cash"}]).topTen.length,0);
 const combined=mergeInputs([{state:"ready",attempts:0,input:{ticker:"AAPL",name:"Apple",kind:"stock",shares:1,price:10}},{state:"ready",attempts:0,input:{ticker:"AAPL",name:"Apple",kind:"stock",shares:1,price:20}}]);
 assert.equal(combined[0].shares*combined[0].price,30);

 const db=new PGlite();
 await db.exec(`create role anon; create role authenticated; create role service_role;
 create schema auth; create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;`);
 await db.exec(await readFile(new URL('../supabase/migrations/20260926000000_accounts.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../supabase/migrations/20260926000100_imports.sql',import.meta.url),'utf8'));
 const owner="00000000-0000-4000-8000-000000000001", id="00000000-0000-4000-8000-000000000002", second="00000000-0000-4000-8000-000000000003";
 await db.query('insert into auth.users values($1)',[owner]);
 await db.query("insert into public.portfolios(user_id,name,kind) values($1,'Existing portfolio','real')",[owner]);
 for(const job of [id,second])await db.query(`insert into import_jobs(id,owner_id,source,original,rows,original_csv,original_hash) values($1,$2,'rows',$3,$3,'csv','hash')`,[job,owner,JSON.stringify([a])]);
 const confirm=async(job:string)=>db.query<{id:string}>(`select confirm_import($1,$2,0,$3,'csv','hash','identity','identityhash') as id`,[job,owner,JSON.stringify([a])]);
 assert.equal((await confirm(id)).rows[0].id,id);
 assert.equal((await confirm(second)).rows[0].id,id);
 assert.equal((await db.query('select * from import_portfolios')).rows.length,1);
 assert.equal((await db.query<{name:string}>('select name from public.portfolios')).rows[0].name,'Existing portfolio');
 let claim=(await db.query<{id:string;lease_token:string}>('select * from claim_import()')).rows[0];
 assert.equal(claim.id,id);
 assert.equal((await db.query('select * from claim_import()')).rows.length,0);
 await db.query(`select checkpoint_import($1,$2,'[{"state":"pending","attempts":1}]')`,[id,claim.lease_token]);
 const expiredToken=claim.lease_token;
 await db.query(`update import_jobs set lease_until=now()-interval '1 second' where id=$1`,[id]);
 const recovered=(await db.query<{id:string;lease_token:string;results:{attempts:number}[]}>('select * from claim_import()')).rows[0];
 assert.equal(recovered.results[0].attempts,1);assert.notEqual(recovered.lease_token,expiredToken);claim=recovered;
 const results=JSON.stringify([{state:"ready",attempts:0}]);
 const stale=await db.query<{ok:boolean}>(`select save_import_work($1,$2,$3,'complete',now(),'{}') as ok`,[id,second,results]);
 assert.equal(stale.rows[0].ok,false);
 await assert.rejects(db.query(`select save_import_work($1,$2,'[]','complete',now(),'{}')`,[id,claim.lease_token]));
 const saved=await db.query<{ok:boolean}>(`select save_import_work($1,$2,$3,'complete',now(),'{}') as ok`,[id,claim.lease_token,results]);
 assert.equal(saved.rows[0].ok,true);
 assert.equal((await db.query('select * from portfolio_snapshots')).rows.length,1);
 assert.equal((await db.query<{ok:boolean}>(`select save_import_work($1,$2,$3,'complete',now(),'{}') as ok`,[id,claim.lease_token,results])).rows[0].ok,false);
 for(let i=0;i<55;i++)assert.equal((await db.query<{retry:string|null}>(`select reserve_provider('finnhub',55,60) as retry`)).rows[0].retry,null);
 assert.ok((await db.query<{retry:string|null}>(`select reserve_provider('finnhub',55,60) as retry`)).rows[0].retry);
 const firstClaim=await db.query<{result:{state:string}}>(`select claim_provider_cache('quote:AAPL',$1) as result`,[id]);
 assert.equal(firstClaim.rows[0].result.state,"claimed");
 assert.equal((await db.query<{result:{state:string}}>(`select claim_provider_cache('quote:AAPL',$1) as result`,[second])).rows[0].result.state,"waiting");
 await db.query(`select finish_provider_cache('quote:AAPL',$1,'{"result":{"price":123}}',now()+interval '1 minute')`,[id]);
 assert.equal((await db.query<{result:{state:string}}>(`select claim_provider_cache('quote:AAPL',$1) as result`,[second])).rows[0].result.state,"cached");
 const imageId="00000000-0000-4000-8000-000000000004";
 await db.query(`select save_screenshot($1,$2,$3,'csv','hash','image/png','temporary',import_epoch($2))`,[imageId,owner,JSON.stringify([a])]);
 assert.equal((await db.query('select * from import_images')).rows.length,1);
 await confirm(imageId);
 assert.equal((await db.query('select * from import_images')).rows.length,0);
 await db.query('select cancel_import_drafts($1,null)',[owner]);
 await assert.rejects(db.query(`select save_screenshot($1,$2,$3,'csv','hash','image/png','temporary',0)`,["00000000-0000-4000-8000-000000000005",owner,JSON.stringify([a])]));
 const rls=await db.query<{relrowsecurity:boolean}>("select relrowsecurity from pg_class where relname='portfolio_snapshots'");
 assert.equal(rls.rows[0].relrowsecurity,true);
 await db.exec(`grant usage on schema auth to authenticated; set role authenticated;`);
 await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[owner]);
 assert.equal((await db.query('select * from portfolio_snapshots')).rows.length,1);
 await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[second]);
 assert.equal((await db.query('select * from portfolio_snapshots')).rows.length,0);
 await assert.rejects(db.query(`select * from claim_import()`));
 await db.exec('reset role');
 await db.close();
 console.log("Import checks passed: row preservation, identity, valuation isolation, cash denominator, migration, job deduplication, lease fencing, snapshot atomicity and quota.");
}
main().catch(e=>{console.error(e);process.exitCode=1;});
