import assert from "node:assert/strict";
import { auditApiProvenance } from "../src/lib/api-provenance";
import type { Provenance } from "../src/lib/provenance";

const input: Provenance = { kind: "retrieved", provider: "user-import", retrievedAt: "2026-09-27T00:00:00Z", source: "User-reviewed test input" };
const computed: Provenance = { kind: "computed", formula: "shares × price", inputs: [input] };
const payload = { total: 100, rows: [{ price: 10, shares: 10, numericProvenance: { "/price": input, "/shares": input } }], numericProvenance: { "/total": computed } };
assert.equal(auditApiProvenance(payload).numericFields, 3);
assert.equal(auditApiProvenance({ total: 100, provenance: { "/total": computed } }).numericFields, 1);
assert.equal(auditApiProvenance({ data: { value: 1 }, provenance: { "/value": input } }).numericFields, 1);
assert.equal(auditApiProvenance({ value: 10, provenance: input }).numericFields, 1);
assert.equal(auditApiProvenance({ count: 1, provenance: { latest: input, prior: input }, numericProvenance: { "/count": computed } }).numericFields, 1);
assert.throws(() => auditApiProvenance({ count: 1, provenance: { latest: input, prior: input } }), /missing.*count/i);
assert.throws(() => auditApiProvenance({ provenance: { latest: { ...input, hiddenNumber: 1 } } }), /metadata/i);
assert.throws(() => auditApiProvenance({ provenance: { latest: input, "/count": input } }), /mixed/i);
assert.throws(() => auditApiProvenance({ total: 1, provenance: { total: input } }), /missing.*total/i);
assert.throws(() => auditApiProvenance({ provenance: { kind: input, prior: input } }), /kind/i);
assert.throws(() => auditApiProvenance({ data: {}, total: 1, provenance: { "/total": input } }), /missing.*total/i);
assert.equal(auditApiProvenance({ data: {}, total: 1, numericProvenance: { "/total": input } }).numericFields, 1);
const reordered = Object.fromEntries(Object.entries(input).reverse());
assert.equal(auditApiProvenance({ value: 10, provenance: input, numericProvenance: { "/value": reordered } }).numericFields, 1);
assert.throws(() => auditApiProvenance({ value: 10, provenance: input, numericProvenance: { "/value": { ...input, source: "Different reviewed input" } } }), /conflicting/i);
assert.throws(() => auditApiProvenance({ value: 10, another: 20, provenance: input }), /\/another/);
assert.throws(() => auditApiProvenance({ total: 100 }), /\/total/);
assert.throws(() => auditApiProvenance({ price: 10, provenance: input }), /\/price/);
assert.throws(() => auditApiProvenance({ rows: [1], numericProvenance: { "/rows": input } }), /\/rows\/0/);
assert.throws(() => auditApiProvenance({ total: Infinity, numericProvenance: { "/total": computed } }), /finite/);
assert.throws(() => auditApiProvenance({ numericProvenance: { "/missing": input } }), /orphan/i);
assert.throws(() => auditApiProvenance({ value: 10, provenance: { ...input, hiddenNumber: 42 } }), /metadata/i);
assert.throws(() => auditApiProvenance({ value: 10, numericProvenance: { "/value": { kind: "computed", formula: "x", inputs: [] } } }), /provenance/i);
assert.throws(() => auditApiProvenance({ error: { code: "UNAVAILABLE", message: "Provider failed" } }), /error response/i);
assert.throws(() => auditApiProvenance({ type: "error", error: "Provider failed" }), /error response/i);
assert.equal(auditApiProvenance({ type: "progress", message: "Reading filing" }).numericFields, 0);
console.log("API provenance audit contract OK: exact numeric leaves, nested evidence, envelopes, no hidden numbers or vacuous error passes");
